# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ucount_IOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'Charts'

  # Pods for Ucount_IOS

  target 'Ucount_IOSTests' do
    inherit! :search_paths
    # Pods for testing
    
  end

  target 'Ucount_IOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
